/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *                                                                           * 
 * Code massaged by Giulio Dujany - University of Manchester                 *
 *****************************************************************************/

#ifndef ROODSCBSHAPE
#define ROODSCBSHAPE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooDSCBShape : public RooAbsPdf {
public:
  RooDSCBShape() {} ; 
  RooDSCBShape(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mu,
	      RooAbsReal& _sig,
	      RooAbsReal& _a1,
	      RooAbsReal& _n1,
	      RooAbsReal& _a2,
	      RooAbsReal& _n2);
  RooDSCBShape(const RooDSCBShape& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooDSCBShape(*this,newname); }
  inline virtual ~RooDSCBShape() { }

protected:

  RooRealProxy x ;
  RooRealProxy mu ;
  RooRealProxy sig ;
  RooRealProxy a1 ;
  RooRealProxy n1 ;
  RooRealProxy a2 ;
  RooRealProxy n2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooDSCBShape,1) // Your description goes here...
};
 
#endif