/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYROODOUBLECBSHAPE
#define MYROODOUBLECBSHAPE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooMyPDF_DSCB : public RooAbsPdf {
public:
  RooMyPDF_DSCB() {} ; 
  RooMyPDF_DSCB(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alphaL,
	      RooAbsReal& _expL,
	      RooAbsReal& _alphaR,
	      RooAbsReal& _expR);
  RooMyPDF_DSCB(const RooMyPDF_DSCB& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMyPDF_DSCB(*this,newname); }
  inline virtual ~RooMyPDF_DSCB() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy alphaL ;
  RooRealProxy expL ;
  RooRealProxy alphaR ;
  RooRealProxy expR ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooMyPDF_DSCB,1) // Your description goes here...
};
 
#endif